### ISSUE TITLE
item.delete

### ISSUE THREAD

**Issue by Romi36** [Azure/azure-cosmos-js#361]
Hello, 

I'm trying to delete some items from my azure cosmo DB but I can't. This is my code : 
```
var dbName = cosmoService.getDatabase(req.headers.environnement);
var query = {query: "SELECT * FROM root r"};
        var container = clientDB.database(dbName).container('ModuleDocument');
        container.items.query(query, { enableCrossPartitionQuery: true }).toArray().then(function(results){
  results.result.forEach(function(document){
  try {
     if(req.headers.remove){
        var item = container.item(document);
        item.delete(document.id).catch(function(err){console.log(err);})
     }
  } catch (error) {
    console.log(error);
 }
});
```

This is my error : 
```
Error: invalid input: input is not string
    at Function.trimSlashFromLeftAndRight (*****/node_modules/@azure/cosmos/lib/src/common/helper.js:231:19)
    at Function.createDocumentUri (*****/node_modules/@azure/cosmos/lib/src/common/uriFactory.js:60:32)
    at Item.get url [as url] (*****/node_modules/@azure/cosmos/lib/src/client/Item/Item.js:27:36)
    at Item.<anonymous> (*****/node_modules/@azure/cosmos/lib/src/client/Item/Item.js:77:63)
    at Generator.next (<anonymous>)
    at *****/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/*****/node_modules/tslib/tslib.js:103:16)
    at Item.delete (*****/node_modules/@azure/cosmos/lib/src/client/Item/Item.js:72:24)
    at *****/routes/security.js:49:34
```

Environnement variables : 
    "@azure/cosmos": "^2.1.7",
    Node : v12.4.0
    npm : 6.9.0

Have you some information ? 
Thanks !

**Comment by southpolesteve** [comment]
@Romi36 I haven't had a chance to run your code yet, but I think the line:

`var item = container.item(document);`

Should be:

`var item = container.item(document.id);`

In any case, this is a bad error, we will doing something to improve it.

**Comment by southpolesteve** [comment]
Gonna close this and continue in https://github.com/Azure/azure-cosmos-js/issues/42
