### ISSUE TITLE
Error 404 when deleting a document

### ISSUE THREAD

**Issue by jeverduzco** [Azure/azure-cosmos-js#376]
Hi, I don't know if this is the right place to put this but I can't find a solution.

I am trying to delete a document following the guide that is here: [https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-get-started#DeleteItem](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-get-started#DeleteItem)

I have this code in my azure function:

```
const cosmos = require("@azure/cosmos");
const CosmosClient = cosmos.CosmosClient;
 
const endpoint = process.env["CosmosDBString"];
const masterKey = process.env["CosmosDBKey"];
const client = new CosmosClient({ endpoint, key: masterKey });

const databaseId = "mydatabase";
const containerId = "mycollection";

module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    if (req.body.id) {
        const docId = req.body.id
        await client.database(databaseId).container(containerId).item(docId).delete(docId);
        context.res = {
            status: 200,
            body: "Removed"
        };
        context.done();
    }
    else {
        context.res = {
            status: 400,
            body: "No comment ID"
        };
        context.done();
    }
};
```

But when I run it passing a correct id that if it exists in the database (I can check if I use the data explorer) I return this error:
```

2019-07-18T03:14:21.126 [Error] Executed 'Functions.ver-delete-post-comment' (Failed, Id=75ed3c6f-deb9-4225-8037-ee464cdfc5f7)
Result: Failure
Exception: Error: Entity with the specified id does not exist in the system., 
RequestStartTime: 2019-07-18T03:14:20.9605630Z, RequestEndTime: 2019-07-18T03:14:20.9705456Z, Number of regions attempted: 1
ResponseTime: 2019-07-18T03:14:20.9705456Z, StoreResult: StorePhysicalAddress: rntbd://sn2prdddc02-docdb-1.documents.azure.com:16735/apps/7dc938ac-8c47-4af3-9760-5e80284624b0/services/b5cee028-8b44-4652-863f-204af39fafba/partitions/09d7a2b9-bed0-436a-b5fb-05a35db387fb/replicas/132037369452646895p/, LSN: 909006, GlobalCommittedLsn: 909006, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#909006, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Delete
, Microsoft.Azure.Documents.Common/2.4.0.0
Stack: Error: Entity with the specified id does not exist in the system., 
RequestStartTime: 2019-07-18T03:14:20.9605630Z, RequestEndTime: 2019-07-18T03:14:20.9705456Z, Number of regions attempted: 1
ResponseTime: 2019-07-18T03:14:20.9705456Z, StoreResult: StorePhysicalAddress: rntbd://sn2prdddc02-docdb-1.documents.azure.com:16735/apps/7dc938ac-8c47-4af3-9760-5e80284624b0/services/b5cee028-8b44-4652-863f-204af39fafba/partitions/09d7a2b9-bed0-436a-b5fb-05a35db387fb/replicas/132037369452646895p/, LSN: 909006, GlobalCommittedLsn: 909006, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#909006, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Delete
, Microsoft.Azure.Documents.Common/2.4.0.0
    at D:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:6303:39
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\tslib\tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What am I doing wrong?
Or maybe it's a bug?

**Comment by southpolesteve** [comment]
@jeverduzco What version of the SDK are you using? Is the container partitioned and does the item have a partition key specified? 

If it is partitioned you need to use the partition key value as the second argument to item:

`await client.database(databaseId).container(containerId).item(id, partitionKey).delete()`

**Comment by jeverduzco** [comment]
Hi @southpolesteve you're my hero, that's what I was missing.

I'm using version 3.0.3.
