### ISSUE TITLE
using dependency that implements "async"

### ISSUE THREAD

**Issue by SoulKa** [Azure/azure-cosmos-js#380]
Since the new major I can't use this node module anymore. I am using node version 6 that does not support async/await.

The new major version seems to use "crypto-hash" which has an async function and is not usable with node version 6.

/var/js_v6/AddOns/cloudDB-connector/node_modules/crypto-hash/index.js:4
const create = algorithm => async (buffer, options) => {
                                  ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /var/js_v6/AddOns/cloudDB-connector/node_modules/@azure/cosmos/dist/index.js:2:250

**Comment by southpolesteve** [comment]
@SoulKa sorry you ran into this. I forgot to add it to the release notes. In v3, we have dropped Node 6 support, as it reached the End of Life (EOL) stage and is no longer supported by the Node.js project. We will continue to support node 6 on the 2.x.x releases. You could also run babel over your `node_modules` folder which is what we do for some internal apps that use v3 but also need to support IE usage.
